#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../resources/TempWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TempWindow(object):
    def setupUi(self, TempWindow):
        TempWindow.setObjectName("TempWindow")
        TempWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TempWindow.sizePolicy().hasHeightForWidth())
        TempWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(TempWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.FieldView = QtWidgets.QGraphicsView(self.centralwidget)
        self.FieldView.setGeometry(QtCore.QRect(10, 40, 900, 600))
        self.FieldView.setAutoFillBackground(False)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.FieldView.setBackgroundBrush(brush)
        self.FieldView.setObjectName("FieldView")
        self.CameraView = QtWidgets.QGraphicsView(self.centralwidget)
        self.CameraView.setGeometry(QtCore.QRect(940, 40, 320, 240))
        self.CameraView.setObjectName("CameraView")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(950, 300, 301, 321))
        self.widget.setObjectName("widget")
        self.Command_Ver = QtWidgets.QVBoxLayout(self.widget)
        self.Command_Ver.setContentsMargins(0, 0, 0, 0)
        self.Command_Ver.setObjectName("Command_Ver")
        self.Robot1_Ver = QtWidgets.QVBoxLayout()
        self.Robot1_Ver.setObjectName("Robot1_Ver")
        self.Robot1_Des_Hor = QtWidgets.QHBoxLayout()
        self.Robot1_Des_Hor.setObjectName("Robot1_Des_Hor")
        self.Robot1 = QtWidgets.QLabel(self.widget)
        self.Robot1.setObjectName("Robot1")
        self.Robot1_Des_Hor.addWidget(self.Robot1)
        self.Robot1_Con = QtWidgets.QPushButton(self.widget)
        self.Robot1_Con.setObjectName("Robot1_Con")
        self.Robot1_Des_Hor.addWidget(self.Robot1_Con)
        self.Robot1_Cam = QtWidgets.QPushButton(self.widget)
        self.Robot1_Cam.setObjectName("Robot1_Cam")
        self.Robot1_Des_Hor.addWidget(self.Robot1_Cam)
        self.Robot1_Ver.addLayout(self.Robot1_Des_Hor)
        self.Robot1_Pos_Hor = QtWidgets.QHBoxLayout()
        self.Robot1_Pos_Hor.setObjectName("Robot1_Pos_Hor")
        self.Robot1_X = QtWidgets.QLabel(self.widget)
        self.Robot1_X.setObjectName("Robot1_X")
        self.Robot1_Pos_Hor.addWidget(self.Robot1_X)
        self.Robot1_Xnum = QtWidgets.QLabel(self.widget)
        self.Robot1_Xnum.setObjectName("Robot1_Xnum")
        self.Robot1_Pos_Hor.addWidget(self.Robot1_Xnum)
        self.Robot1_Y = QtWidgets.QLabel(self.widget)
        self.Robot1_Y.setObjectName("Robot1_Y")
        self.Robot1_Pos_Hor.addWidget(self.Robot1_Y)
        self.Robot1_Ynum = QtWidgets.QLabel(self.widget)
        self.Robot1_Ynum.setObjectName("Robot1_Ynum")
        self.Robot1_Pos_Hor.addWidget(self.Robot1_Ynum)
        self.Robot1_Ver.addLayout(self.Robot1_Pos_Hor)
        self.Command_Ver.addLayout(self.Robot1_Ver)
        self.Robot2_Ver = QtWidgets.QVBoxLayout()
        self.Robot2_Ver.setObjectName("Robot2_Ver")
        self.Robot2_Des_Hor = QtWidgets.QHBoxLayout()
        self.Robot2_Des_Hor.setObjectName("Robot2_Des_Hor")
        self.Robot2 = QtWidgets.QLabel(self.widget)
        self.Robot2.setObjectName("Robot2")
        self.Robot2_Des_Hor.addWidget(self.Robot2)
        self.Robot2_Con = QtWidgets.QPushButton(self.widget)
        self.Robot2_Con.setObjectName("Robot2_Con")
        self.Robot2_Des_Hor.addWidget(self.Robot2_Con)
        self.Robot2_Cam = QtWidgets.QPushButton(self.widget)
        self.Robot2_Cam.setObjectName("Robot2_Cam")
        self.Robot2_Des_Hor.addWidget(self.Robot2_Cam)
        self.Robot2_Ver.addLayout(self.Robot2_Des_Hor)
        self.Robot2_Pos_Hor = QtWidgets.QHBoxLayout()
        self.Robot2_Pos_Hor.setObjectName("Robot2_Pos_Hor")
        self.Robot2_X = QtWidgets.QLabel(self.widget)
        self.Robot2_X.setObjectName("Robot2_X")
        self.Robot2_Pos_Hor.addWidget(self.Robot2_X)
        self.Robot2_Xnum = QtWidgets.QLabel(self.widget)
        self.Robot2_Xnum.setObjectName("Robot2_Xnum")
        self.Robot2_Pos_Hor.addWidget(self.Robot2_Xnum)
        self.Robot2_Y = QtWidgets.QLabel(self.widget)
        self.Robot2_Y.setObjectName("Robot2_Y")
        self.Robot2_Pos_Hor.addWidget(self.Robot2_Y)
        self.Robot2_Ynum = QtWidgets.QLabel(self.widget)
        self.Robot2_Ynum.setObjectName("Robot2_Ynum")
        self.Robot2_Pos_Hor.addWidget(self.Robot2_Ynum)
        self.Robot2_Ver.addLayout(self.Robot2_Pos_Hor)
        self.Command_Ver.addLayout(self.Robot2_Ver)
        self.Robot3_Ver = QtWidgets.QVBoxLayout()
        self.Robot3_Ver.setObjectName("Robot3_Ver")
        self.Robot3_Des_Hor = QtWidgets.QHBoxLayout()
        self.Robot3_Des_Hor.setObjectName("Robot3_Des_Hor")
        self.Robot3 = QtWidgets.QLabel(self.widget)
        self.Robot3.setObjectName("Robot3")
        self.Robot3_Des_Hor.addWidget(self.Robot3)
        self.Robot3_Con = QtWidgets.QPushButton(self.widget)
        self.Robot3_Con.setObjectName("Robot3_Con")
        self.Robot3_Des_Hor.addWidget(self.Robot3_Con)
        self.Robot3_Cam = QtWidgets.QPushButton(self.widget)
        self.Robot3_Cam.setObjectName("Robot3_Cam")
        self.Robot3_Des_Hor.addWidget(self.Robot3_Cam)
        self.Robot3_Ver.addLayout(self.Robot3_Des_Hor)
        self.Robot3_Pos_Hor = QtWidgets.QHBoxLayout()
        self.Robot3_Pos_Hor.setObjectName("Robot3_Pos_Hor")
        self.Robot3_X = QtWidgets.QLabel(self.widget)
        self.Robot3_X.setObjectName("Robot3_X")
        self.Robot3_Pos_Hor.addWidget(self.Robot3_X)
        self.Robot3_Xnum = QtWidgets.QLabel(self.widget)
        self.Robot3_Xnum.setObjectName("Robot3_Xnum")
        self.Robot3_Pos_Hor.addWidget(self.Robot3_Xnum)
        self.Robot3_Y = QtWidgets.QLabel(self.widget)
        self.Robot3_Y.setObjectName("Robot3_Y")
        self.Robot3_Pos_Hor.addWidget(self.Robot3_Y)
        self.Robot3_Ynum = QtWidgets.QLabel(self.widget)
        self.Robot3_Ynum.setObjectName("Robot3_Ynum")
        self.Robot3_Pos_Hor.addWidget(self.Robot3_Ynum)
        self.Robot3_Ver.addLayout(self.Robot3_Pos_Hor)
        self.Command_Ver.addLayout(self.Robot3_Ver)
        self.Robot4_Ver = QtWidgets.QVBoxLayout()
        self.Robot4_Ver.setObjectName("Robot4_Ver")
        self.Robot4_Des_Hor = QtWidgets.QHBoxLayout()
        self.Robot4_Des_Hor.setObjectName("Robot4_Des_Hor")
        self.Robot4 = QtWidgets.QLabel(self.widget)
        self.Robot4.setObjectName("Robot4")
        self.Robot4_Des_Hor.addWidget(self.Robot4)
        self.Robot4_Con = QtWidgets.QPushButton(self.widget)
        self.Robot4_Con.setObjectName("Robot4_Con")
        self.Robot4_Des_Hor.addWidget(self.Robot4_Con)
        self.Robot4_Cam = QtWidgets.QPushButton(self.widget)
        self.Robot4_Cam.setObjectName("Robot4_Cam")
        self.Robot4_Des_Hor.addWidget(self.Robot4_Cam)
        self.Robot4_Ver.addLayout(self.Robot4_Des_Hor)
        self.Robot4_Pos_Hor = QtWidgets.QHBoxLayout()
        self.Robot4_Pos_Hor.setObjectName("Robot4_Pos_Hor")
        self.Robot4_X = QtWidgets.QLabel(self.widget)
        self.Robot4_X.setObjectName("Robot4_X")
        self.Robot4_Pos_Hor.addWidget(self.Robot4_X)
        self.Robot4_Xnum = QtWidgets.QLabel(self.widget)
        self.Robot4_Xnum.setObjectName("Robot4_Xnum")
        self.Robot4_Pos_Hor.addWidget(self.Robot4_Xnum)
        self.Robot4_Y = QtWidgets.QLabel(self.widget)
        self.Robot4_Y.setObjectName("Robot4_Y")
        self.Robot4_Pos_Hor.addWidget(self.Robot4_Y)
        self.Robot4_Ynum = QtWidgets.QLabel(self.widget)
        self.Robot4_Ynum.setObjectName("Robot4_Ynum")
        self.Robot4_Pos_Hor.addWidget(self.Robot4_Ynum)
        self.Robot4_Ver.addLayout(self.Robot4_Pos_Hor)
        self.Command_Ver.addLayout(self.Robot4_Ver)
        TempWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TempWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        TempWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TempWindow)
        self.statusbar.setObjectName("statusbar")
        TempWindow.setStatusBar(self.statusbar)
        self.actionInitialisation = QtWidgets.QAction(TempWindow)
        self.actionInitialisation.setObjectName("actionInitialisation")
        self.actionClose = QtWidgets.QAction(TempWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuOption.addAction(self.actionInitialisation)
        self.menuOption.addAction(self.actionClose)
        self.menubar.addAction(self.menuOption.menuAction())

        self.retranslateUi(TempWindow)
        QtCore.QMetaObject.connectSlotsByName(TempWindow)

    def retranslateUi(self, TempWindow):
        _translate = QtCore.QCoreApplication.translate
        TempWindow.setWindowTitle(_translate("TempWindow", "MainWindow"))
        self.Robot1.setText(_translate("TempWindow", "Robot1"))
        self.Robot1_Con.setText(_translate("TempWindow", "Connect"))
        self.Robot1_Cam.setText(_translate("TempWindow", "Show Camera"))
        self.Robot1_X.setText(_translate("TempWindow", "X(m) :"))
        self.Robot1_Xnum.setText(_translate("TempWindow", "0.0"))
        self.Robot1_Y.setText(_translate("TempWindow", "Y(m):"))
        self.Robot1_Ynum.setText(_translate("TempWindow", "0.0"))
        self.Robot2.setText(_translate("TempWindow", "Robot2"))
        self.Robot2_Con.setText(_translate("TempWindow", "Connect"))
        self.Robot2_Cam.setText(_translate("TempWindow", "Show Camera"))
        self.Robot2_X.setText(_translate("TempWindow", "X(m) :"))
        self.Robot2_Xnum.setText(_translate("TempWindow", "0.0"))
        self.Robot2_Y.setText(_translate("TempWindow", "Y(m):"))
        self.Robot2_Ynum.setText(_translate("TempWindow", "0.0"))
        self.Robot3.setText(_translate("TempWindow", "Robot3"))
        self.Robot3_Con.setText(_translate("TempWindow", "Connect"))
        self.Robot3_Cam.setText(_translate("TempWindow", "Show Camera"))
        self.Robot3_X.setText(_translate("TempWindow", "X(m) :"))
        self.Robot3_Xnum.setText(_translate("TempWindow", "0.0"))
        self.Robot3_Y.setText(_translate("TempWindow", "Y(m):"))
        self.Robot3_Ynum.setText(_translate("TempWindow", "0.0"))
        self.Robot4.setText(_translate("TempWindow", "Robot4"))
        self.Robot4_Con.setText(_translate("TempWindow", "Connect"))
        self.Robot4_Cam.setText(_translate("TempWindow", "Show Camera"))
        self.Robot4_X.setText(_translate("TempWindow", "X(m) :"))
        self.Robot4_Xnum.setText(_translate("TempWindow", "0.0"))
        self.Robot4_Y.setText(_translate("TempWindow", "Y(m):"))
        self.Robot4_Ynum.setText(_translate("TempWindow", "0.0"))
        self.menuOption.setTitle(_translate("TempWindow", "Option"))
        self.actionInitialisation.setText(_translate("TempWindow", "Initialisation"))
        self.actionClose.setText(_translate("TempWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TempWindow = QtWidgets.QMainWindow()
    ui = Ui_TempWindow()
    ui.setupUi(TempWindow)
    TempWindow.show()
    sys.exit(app.exec_())

