#!/usr/bin/env python

from behavior_monitor.MainWindow import MonitorWindow
from PyQt5 import QtWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MonitorWindow()
    ui.setupUi(MainWindow)
    ui.setupSlots(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
